<wsdl:definitions
     name="soloEntrada"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/socket/sockets/sockets/soloEntrada"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/socket/sockets/sockets/soloEntrada"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:imp1="http://shrikworld.blogspot.in/ReadEmpDetails"
    >
  <plt:partnerLinkType name="Receive_plt" >
    <plt:role name="Receive_role" >
      <plt:portType name="tns:Receive_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://shrikworld.blogspot.in/ReadEmpDetails" schemaLocation="../Schemas/emp.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Receive_msg">
        <wsdl:part name="body" element="imp1:EmpDetails"/>
    </wsdl:message>
    <wsdl:portType name="Receive_ptt">
        <wsdl:operation name="Receive">
            <wsdl:input message="tns:Receive_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
