package xmlns.oracle.com.pcbpel.adapter.socket.sockets.sockets.transparente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build build (050908.2342.55399))

@WebService(targetNamespace =
            "http://xmlns.oracle.com/pcbpel/adapter/socket/sockets/sockets/Transparente",
            name = "InboundRequestReply_ptt")
@XmlSeeAlso({ com.oracle.xmlns.pcbpel.adapter.opaque.ObjectFactory.class })
public interface InboundRequestReply_ptt
{
  @WebMethod(operationName = "InboundRequestReply")
  @SOAPBinding(parameterStyle = ParameterStyle.BARE)
  @Action(output =
          "http://xmlns.oracle.com/pcbpel/adapter/socket/sockets/sockets/Transparente/InboundRequestReply_ptt/InboundRequestReplyResponse",
          input =
          "http://xmlns.oracle.com/pcbpel/adapter/socket/sockets/sockets/Transparente/InboundRequestReply_ptt/InboundRequestReplyRequest")
  public void inboundRequestReply(@WebParam(mode = Mode.INOUT,
                                            targetNamespace =
                                            "http://xmlns.oracle.com/pcbpel/adapter/opaque/",
                                            name = "opaqueElement",
                                            partName = "opaque")
                                  javax.xml.ws.Holder<byte[]> opaque);
}
