package xmlns.oracle.com.pcbpel.adapter.socket.sockets.sockets.entrada;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build build (050908.2342.55399))

@WebService(targetNamespace =
            "http://xmlns.oracle.com/pcbpel/adapter/socket/sockets/sockets/entrada",
            name = "InboundRequestReply_ptt")
@XmlSeeAlso({ in.blogspot.shrikworld.response.ObjectFactory.class,
              in.blogspot.shrikworld.readempdetails.ObjectFactory.class })
public interface InboundRequestReply_ptt
{
  @WebMethod(operationName = "InboundRequestReply")
  @SOAPBinding(parameterStyle = ParameterStyle.BARE)
  @Action(output =
          "http://xmlns.oracle.com/pcbpel/adapter/socket/sockets/sockets/entrada/InboundRequestReply_ptt/InboundRequestReplyResponse",
          input =
          "http://xmlns.oracle.com/pcbpel/adapter/socket/sockets/sockets/entrada/InboundRequestReply_ptt/InboundRequestReplyRequest")
  @WebResult(targetNamespace = "http://shrikworld.blogspot.in/response",
             name = "Response", partName = "Response")
  public in.blogspot.shrikworld.response.Response inboundRequestReply(@WebParam(targetNamespace =
                                                                                "http://shrikworld.blogspot.in/ReadEmpDetails",
                                                                                name =
                                                                                "EmpDetails",
                                                                                partName =
                                                                                "EmpDetails")
                                                                      in.blogspot.shrikworld.readempdetails.EmpDetails EmpDetails);
}
