package interfaces.example.soa.euge;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build build (050908.2342.55399))

@WebService(targetNamespace = "http://interfaces.example.soa.euge/",
            name = "servicioPersona")
@XmlSeeAlso({ euge.soa.example.interfaces.ObjectFactory.class,
              euge.soa.example.interfaces.types.ObjectFactory.class })
public interface ServicioPersona
{
  @WebMethod
  @SOAPBinding(parameterStyle = ParameterStyle.BARE)
  @Action(output = "", input = "")
  @WebResult(targetNamespace = "http://interfaces.example.soa.euge/",
             name = "notificaResponse", partName = "parameters")
  public euge.soa.example.interfaces.NotificaResponse notifica(@WebParam(targetNamespace =
                                                                         "http://interfaces.example.soa.euge/",
                                                                         name =
                                                                         "notifica",
                                                                         partName =
                                                                         "parameters")
                                                               euge.soa.example.interfaces.Notifica parameters);

  @WebMethod
  @SOAPBinding(parameterStyle = ParameterStyle.BARE)
  @Action(output = "", input = "")
  @WebResult(targetNamespace = "http://interfaces.example.soa.euge/",
             name = "checkPersonaResponse", partName = "parameters")
  public euge.soa.example.interfaces.CheckPersonaResponse checkPersona(@WebParam(targetNamespace =
                                                                                 "http://interfaces.example.soa.euge/",
                                                                                 name =
                                                                                 "checkPersona",
                                                                                 partName =
                                                                                 "parameters")
                                                                       euge.soa.example.interfaces.CheckPersona parameters);
}
