package xmlns.oracle.com.sockets.sockets.implementaservicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build build (050908.2342.55399))

@WebService(targetNamespace =
            "http://xmlns.oracle.com/sockets/sockets/implementaServicio",
            name = "implementaServicio")
@XmlSeeAlso({ com.oracle.xmlns.sockets.sockets.implementaservicio.ObjectFactory.class })
public interface ImplementaServicio
{
  @WebMethod
  @SOAPBinding(parameterStyle = ParameterStyle.BARE)
  @Action(output =
          "http://xmlns.oracle.com/sockets/sockets/implementaServicio/implementaServicio/processResponse",
          input =
          "http://xmlns.oracle.com/sockets/sockets/implementaServicio/implementaServicio/processRequest")
  @WebResult(targetNamespace =
             "http://xmlns.oracle.com/sockets/sockets/implementaServicio",
             name = "processResponse", partName = "payload")
  public com.oracle.xmlns.sockets.sockets.implementaservicio.ProcessResponse process(@WebParam(targetNamespace =
                                                                                               "http://xmlns.oracle.com/sockets/sockets/implementaServicio",
                                                                                               name =
                                                                                               "process",
                                                                                               partName =
                                                                                               "payload")
                                                                                     com.oracle.xmlns.sockets.sockets.implementaservicio.Process payload);
}
