<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:stat="http://www.oracle.com/XSL/Transform/java/soa.cookbook.xpath.StdDev" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://shrikworld.blogspot.in/ReadEmpDetails" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 mhdr oraext stat xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/socket/sockets/sockets/soloEntrada"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/socket/sockets/sockets/entrada"
                xmlns:msg_reply="http://shrikworld.blogspot.in/response" xml:id="id_1" oraxsl:ignorexmlids="true">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../WSDLs/soloEntrada.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="EmpDetails" namespace="http://shrikworld.blogspot.in/ReadEmpDetails"
                                           xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../WSDLs/entrada.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="EmpDetails" namespace="http://shrikworld.blogspot.in/ReadEmpDetails"
                                           xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [SAT SEP 22 13:42:12 CEST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/" xml:id="id_11">
      <ns0:EmpDetails xml:id="id_12">
         <ns0:usuario xml:id="id_13">
            <xsl:value-of select="/ns0:EmpDetails/ns0:usuario" xml:id="id_14"/>
         </ns0:usuario>
         <ns0:contrasena xml:id="id_15">
            <xsl:value-of select="/ns0:EmpDetails/ns0:contrasena" xml:id="id_16"/>
         </ns0:contrasena>
         <xsl:for-each select="/ns0:EmpDetails/ns0:Emp" xml:id="id_17">
            <ns0:Emp xml:id="id_18">
               <ns0:FirstName xml:id="id_19">
                  <xsl:value-of select="ns0:FirstName" xml:id="id_20"/>
               </ns0:FirstName>
               <ns0:LastName xml:id="id_21">
                  <xsl:value-of select="ns0:LastName" xml:id="id_22"/>
               </ns0:LastName>
               <ns0:Age xml:id="id_23">
                  <xsl:value-of select="ns0:Age" xml:id="id_24"/>
               </ns0:Age>
               <ns0:DOB xml:id="id_25">
                  <xsl:value-of select="ns0:DOB" xml:id="id_26"/>
               </ns0:DOB>
               <ns0:Salary xml:id="id_27">
                  <xsl:value-of select="ns0:Salary" xml:id="id_28"/>
               </ns0:Salary>
            </ns0:Emp>
         </xsl:for-each>
      </ns0:EmpDetails>
   </xsl:template>
</xsl:stylesheet>
